package cu.db.cache;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "CACHE".
 */
public class Cache {

    private Long id;
    /**
     * Not-null value.
     */
    private String key;
    /**
     * Not-null value.
     */
    private String value;
    private Long timeout;
    private Long currentTime;

    public Cache() {
    }

    public Cache(Long id) {
        this.id = id;
    }

    public Cache(Long id, String key, String value, Long timeout, Long currentTime) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.timeout = timeout;
        this.currentTime = currentTime;
    }

    public Cache(String key, String value) {
        this.key = key;
        this.value = value;
        this.currentTime = System.currentTimeMillis();
    }

    public Cache(String key, String value, long timeout) {
        this.key = key;
        this.value = value;
        this.timeout = timeout;
        this.currentTime = System.currentTimeMillis();
    }

    public boolean isTimeout(){
        if (timeout == 0) {
            return false;
        }
        if (System.currentTimeMillis() - currentTime < timeout) {
            return false;
        }
        return true;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getKey() {
        return key;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Not-null value.
     */
    public String getValue() {
        return value;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setValue(String value) {
        this.value = value;
    }

    public Long getTimeout() {
        return timeout;
    }

    public void setTimeout(Long timeout) {
        this.timeout = timeout;
    }

    public Long getCurrentTime() {
        return currentTime;
    }

    public void setCurrentTime(Long currentTime) {
        this.currentTime = currentTime;
    }

}
